name: Health check

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jest:
    name: Unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: borales/actions-yarn@v5.0.0
        with:
          cmd: install --pure-lockfile
      - name: Run tests with coverage
        run: yarn test:coverage --coverageReporters json-summary
      - name: Jest coverage comment
        uses: MishaKav/jest-coverage-comment@v1
        with:
          coverage-summary-path: ./.coverage/coverage-summary.json

  eslint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: ESLint
        uses: reviewdog/action-eslint@v1.34.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          eslint_flags: index.js src/
