name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: Semantic release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.GH_TOKEN_NELSON }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps
        uses: borales/actions-yarn@v5.0.0
        with:
          cmd: install --pure-lockfile
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v4.1.0
        env:
          GIT_AUTHOR_NAME: ${{ secrets.GIT_USERNAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_USERNAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_NELSON }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        with:
          semantic_version: 17.0.7
          extra_plugins: |
            @semantic-release/exec@5.0.0
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0.0
